### ISSUE TITLE
Github Profile Update

### ISSUE THREAD

**Issue by Eccb7** [rubydevi/rubydevi#1]
Hi @rubydevi :wave: 

<img src="https://media4.giphy.com/media/26BRBKqUiq586bRVm/giphy.gif"/>

An amazing effort here on your README file. KUDOS
Though there be some matters that you can take into consideration to make it more professional:
- You can add the Stacks you've used in your projects and an inclusion over the same can be the stack icons.
- It would be nice to add social media links to your README file to connect you easily with potential employers. 
- It would be nice if you added the GitHub Stats to show full stats on what's in your account.
- We would advise you to add a way on how to reach you, that is a dev email to easily get to you.
- It would be nice if you add Topics that are to appear in the form of tags.

**Comment by rubydevi** [comment]
Thanks for this review, I have resolved it :)
